// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"encoding/json"
	"time"
)

type Safe struct {
	ID      int64
	UserID  string
	Name    string
	State   json.RawMessage
	SavedAt time.Time
}

type User struct {
	ID        string
	Email     string
	CreatedAt time.Time
}
