// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: saves.sql

package sqlite

import (
	"context"
	"encoding/json"
	"time"
)

const createSave = `-- name: CreateSave :one
INSERT INTO saves (user_id, name, state) VALUES (?, ?, ?) RETURNING id, user_id, name, state, saved_at
`

type CreateSaveParams struct {
	UserID string
	Name   string
	State  json.RawMessage
}

func (q *Queries) CreateSave(ctx context.Context, arg CreateSaveParams) (Safe, error) {
	row := q.db.QueryRowContext(ctx, createSave, arg.UserID, arg.Name, arg.State)
	var i Safe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.SavedAt,
	)
	return i, err
}

const deleteSave = `-- name: DeleteSave :exec
DELETE FROM saves WHERE id = ? AND user_id = ?
`

type DeleteSaveParams struct {
	ID     int64
	UserID string
}

func (q *Queries) DeleteSave(ctx context.Context, arg DeleteSaveParams) error {
	_, err := q.db.ExecContext(ctx, deleteSave, arg.ID, arg.UserID)
	return err
}

const getSave = `-- name: GetSave :one
SELECT id, user_id, name, state, saved_at FROM saves WHERE id = ? AND user_id = ?
`

type GetSaveParams struct {
	ID     int64
	UserID string
}

func (q *Queries) GetSave(ctx context.Context, arg GetSaveParams) (Safe, error) {
	row := q.db.QueryRowContext(ctx, getSave, arg.ID, arg.UserID)
	var i Safe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.State,
		&i.SavedAt,
	)
	return i, err
}

const listSaves = `-- name: ListSaves :many
SELECT id, user_id, name, saved_at FROM saves WHERE user_id = ? ORDER BY saved_at DESC
`

type ListSavesRow struct {
	ID      int64
	UserID  string
	Name    string
	SavedAt time.Time
}

func (q *Queries) ListSaves(ctx context.Context, userID string) ([]ListSavesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSaves, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavesRow
	for rows.Next() {
		var i ListSavesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.SavedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSave = `-- name: UpdateSave :exec
UPDATE saves SET name = ?, state = ?, saved_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?
`

type UpdateSaveParams struct {
	Name   string
	State  json.RawMessage
	ID     int64
	UserID string
}

func (q *Queries) UpdateSave(ctx context.Context, arg UpdateSaveParams) error {
	_, err := q.db.ExecContext(ctx, updateSave,
		arg.Name,
		arg.State,
		arg.ID,
		arg.UserID,
	)
	return err
}
